### ISSUE TITLE
agregar un mini-tutorial de cómo usar `ab` en la sección de https://github.com/arquitecturas-concurrentes/iasc-practica-ruby/tree/main#c%C3%B3mo-probar-el-servidor

### ISSUE THREAD

**Issue by bossiernesto** [arquitecturas-concurrentes/iasc-practica-ruby#38]
Y podríamos agregar un mini-tutorial de cómo usar `ab` en la sección de https://github.com/arquitecturas-concurrentes/iasc-practica-ruby/tree/main#c%C3%B3mo-probar-el-servidor

_Originally posted by @nrainhart in https://github.com/arquitecturas-concurrentes/iasc-practica-ruby/pull/37#discussion_r1167584058_

**Comment by nrainhart** [comment]
¡Hecho! 16e55b2
